// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgSxiBrhdhfH2WXSY9oP8nGcmka9outz8',
    appId: '1:927879685928:web:affcdf19bc60af2329521d',
    messagingSenderId: '927879685928',
    projectId: 'ditonton-98fee',
    authDomain: 'ditonton-98fee.firebaseapp.com',
    storageBucket: 'ditonton-98fee.appspot.com',
    measurementId: 'G-81ZNZBE527',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxkdbRACVs-3GqjI_O0ty0smOQq7Yk5c',
    appId: '1:927879685928:android:bfcbbedbd8af463e29521d',
    messagingSenderId: '927879685928',
    projectId: 'ditonton-98fee',
    storageBucket: 'ditonton-98fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVO8VmW5msDIQWZhXhUnwiC2qLJUeWxs0',
    appId: '1:927879685928:ios:30245329bcfb9b6e29521d',
    messagingSenderId: '927879685928',
    projectId: 'ditonton-98fee',
    storageBucket: 'ditonton-98fee.appspot.com',
    iosClientId: '927879685928-aq0e72fqef0m9a1ab48ao1ebkicipl5e.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
